"""Enumerations and JSON-Schema validation for v0.6 state objects (schemas in fis/schemas/)."""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
import jsonschema_lite  # noqa: E402

MODES = ("AUTO_CLEAN", "AUDIT_ONLY", "REVIEW_WITH_ME", "HIGH_CONFIDENCE_AUTO_CLEAN", "ACTIVE_SCOUTING")
# Ho Be Gone v0.2: AUTO_CLEAN is the default. Other modes only when the owner asks for them in words (MODE_SOURCE OWNER_WORDS).
WORDS_ONLY_MODES = ("AUDIT_ONLY", "REVIEW_WITH_ME", "HIGH_CONFIDENCE_AUTO_CLEAN")
ENFORCEMENT_MODES = ("AUDIT_ONLY", "REVIEW_WITH_ME", "HIGH_CONFIDENCE_AUTO_CLEAN")  # ACTIVE_SCOUTING maps onto one of these (fis/hbg.py)
DEFAULT_MODE = "AUTO_CLEAN"
ACCOUNT_NATURE = ("HUMAN_LIKELY", "AUTOMATION_LIKELY", "MIXED_OR_ASSISTED", "UNKNOWN")
CLASSIFICATION = ("NORMAL", "SPAM", "SCAM", "IMPERSONATION", "COORDINATED_NETWORK", "REPURPOSED_ACCOUNT")
ENFORCEMENT = ("KEEP", "REVIEW", "BLOCK_CANDIDATE", "BLOCK_CONFIRMED")
OUTCOMES = ("KEEP", "LOW_EVIDENCE_KEEP", "REVIEW", "REVIEW_INSUFFICIENT_DATA", "BLOCK_CANDIDATE", "BLOCK_CONFIRMED", "UNKNOWN")
EVIDENCE_STATES = ("SUFFICIENT", "PARTIAL", "INSUFFICIENT", "UNAVAILABLE")
OWNER_ACTIONS = ("OWNER_ACTION_KEEP", "OWNER_ACTION_BLOCK")
NATURE_LABELS = ("BOT_LIKELY", "HUMAN_LIKELY")
FAILURE_CLASSES = ("COLLECTION_FAILURE", "FEATURE_EXTRACTION_FAILURE", "SCORING_FAILURE", "DECISION_THRESHOLD_FAILURE", "LABEL_AMBIGUITY")
CAL_TAGS = ("HUMAN_CONTINUITY_POSITIVE_CONTROL", "ENGAGEMENT_FARM_REVIEW_CONTROL", "CONFIRMED_COORDINATED_NETWORK",
            "CONFIRMED_IMPERSONATION", "CONFIRMED_SCAM", "LOW_EVIDENCE_UNKNOWN")
BEHAVIOR_TYPES = ("PROFILE_HISTORY", "ORIGINAL_POSTS", "REPLIES", "REPOSTS", "QUOTES", "EXTERNAL_LINKS", "OLDER_CONTENT")
SCORE_NAMES = ("AUTOMATION", "SPAM", "SCAM", "IMPERSONATION", "DECEPTION", "NETWORK_COORDINATION", "HUMAN_CONTINUITY",
               "REPURPOSED_ACCOUNT", "EVIDENCE_COVERAGE")
MALICIOUS_SCORES = ("AUTOMATION", "SPAM", "SCAM", "IMPERSONATION", "DECEPTION")


def load(name):
    with open(os.path.join(HERE, "schemas", name + ".schema.json"), encoding="utf-8") as fh:
        return json.load(fh)


def validate(obj, name):
    """Return a list of problems (empty = valid)."""
    return jsonschema_lite.validate(obj, load(name))
